services:
  rentapp:
    image: docker.io/adylsonrtb/rent-app:1.0.1
    container_name: rent_app
    ports:
      - "8011:80"
    environment:
      API_TARGET: http://localhost:8010
      HEALTH_TARGET: http://localhost:8010
      VEHICLE_TARGET: http://84.247.171.243:8090
